### ISSUE TITLE
Translate to Portuguese (PT-BR)

### ISSUE THREAD

**Issue by Igorcbraz** [Juzlus/KeydropPlus#1]
Hey, i'm from Brazil and i think will be good having portuguese in language options.

I see the "lang" folder on project, my question is if i just need to translate the values of the json. 

Thx

**Comment by Juzlus** [comment]
Yes, if you add a json file, I will be able to add a button integrated with this language. Thank you in advance for your help in developing the project.

**Comment by Igorcbraz** [comment]
You're welcome, i really liked the project btw.

I opened #2  PR, with content about our subject.
